spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/docbridge?useUnicode=true&characterEncoding=utf8mb4
    username: docbridge
    password: docbridge123
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate.format_sql: true
  elasticsearch:
    uris: http://localhost:9200


app:
  jwt:
    secret: your-super-secret-key-min-256-bits-long-here
    expiration: 86400000    # 24h ms

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
